apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user-app
  labels:
    app: udagram-user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-user-app
  template:
    metadata:
      labels:
        app: udagram-user-app
    spec:
      containers:
      - name: udagram-api-user
        image: lodakins/udagram-api-user:v1
        envFrom:
        envFrom:
        - configMapRef:
            name: alx-img-envvar
        - secretRef:
            name: alx-image-secret
        - secretRef:
            name: alx-image-aws-secret
        ports:
        - containerPort: 80
        volumeMounts:
          - name: aws-config
            mountPath: "/.aws:/root/.aws"
            readOnly: true
      volumes:
      - name: aws-config
        secret:
          secretName: alx-image-aws-secret
          optional: false