apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
    type: back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: lodakins/udagram-api-feed:v1
          envFrom:
            - configMapRef:
                name: alx-img-envvar
            - secretRef:
                name: alx-image-secret
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m" 
          volumeMounts:
            - name: aws-config
              mountPath: "./root/.aws"
              readOnly: true
      volumes:
        - name: aws-config
          secret:
            secretName: alx-image-aws-secret
            optional: false
