apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-app
  labels:
    run: udagram-feed-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: udagram-feed-app
      - containerPort: 8080