apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
    type: back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: lodakins/udagram-api-user:v1
          envFrom:
            - configMapRef:
                name: alx-img-envvar
            - secretRef:
                name: alx-image-secret
            - secretRef:
                name: alx-image-aws-secret
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m" 
          volumeMounts:
            - name: aws-config
              mountPath: "./root/.aws"
              readOnly: true
      volumes:
        - name: aws-config
          secret:
            secretName: alx-image-aws-secret
            optional: false
