apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-app
  labels:
    app: reverseproxy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy-app
  template:
    metadata:
      labels:
        app: reverseproxy-app
    spec:
      containers:
      - name: reverseproxy
        image: lodakins/reverseproxy:v1
        ports:
        - containerPort: 8080