apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-app
  labels:
    run: reverseproxy-app
spec:
  ports:
  - name: "reverseproxy-app"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy-app