apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-app
  labels:
    run: reverseproxy-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: reverseproxy-app
      - containerPort: 8080