apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-app
  labels:
    run: reverseproxy-app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: reverseproxy-app
